config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
 root  'topics#index'

 resources :topics do
  resources :comments, only: [:create]
  collection do
    get 'search'
  end
 end

resources :kind_japanese, only: [:index]



end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :sentence_id, numericality: { other_than: 1, message: 'を 選(えら)びましょう' }

  validates :description, presence: { message: 'を 書(か)きましょう' }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :sentence

  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_topic, only: [:edit, :show, :update, :destroy]
  before_action :move_to_index, except: [:index, :show, :new, :create, :search]
  before_action :search_topic, only: [:index, :search]

  def index
    @topics = Topic.includes(:user).order('created_at DESC')
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    if @topic.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @topic.update(topic_params)
      redirect_to topic_path(@topic.id)
    else
      render :edit
    end
  end

  def destroy
    @topic.destroy
  end

  def search
    @results = @p.result.order('created_at DESC')  # 検索条件にマッチした商品の情報を取得
  end

  private

  def topic_params
    params.require(:topic).permit(:sentence_id, :description).merge(user_id: current_user.id)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @topic.user_id
  end

  def search_topic
    @p = Topic.ransack(params[:q])  # 検索オブジェクトを生成
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/destroy.html.erb
<%= render "shared/header" %>

<div class="destroy_main">
    <div class="success">
     <%= link_to root_path do %>
        <ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>消<rt>け</rt></ruby>しました</div>
    <%= image_tag('trash.png',size: '40x40')  %>
    <% end %>
    </div>
</div>

<%= render "shared/footer" %>

app/views/topics/edit.html.erb
<%= render "shared/header" %>

<% breadcrumb :edit_topic, @topic %>

<div class="edit_container">
 <div class="edit_wrapper">

    <%= form_with model:@topic, local: true do |f| %>
   
        <%= render 'shared/error_messages', model: f.object %>

    <div class="new_field">
      <br>
      <div class="choice_sentence">
      <ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>選<rt>えら</rt></ruby>び <ruby>直<rt>なお</rt></ruby>します</div>
      <br>
      
      <%= f.collection_select(:sentence_id, Sentence.all, :id, :name, {}, {class:"select-box", id:"topic_sentence_id"}) %>
      
    </div>

    <br>
    <div class="new_field">
        <div class="explain_sentence"><ruby>私<rt>わたし</rt></ruby>は この<ruby>文章<rt>ぶんしょう</rt></ruby>について <ruby>説明<rt>せつめい</rt></ruby>し <ruby>直<rt>なお</rt></ruby>します</div>
       <br>
        <%= f.text_area :description, autofocus: true, autocomplete: "description" %>
    </div>

      <div class="actions">
       <div><%= button_tag type: :submit ,class: "explain_btn" do %>
        <%= image_tag('explain.png',size: '40x40')  %>
         <% end %>
       </div>
     </div>

</div>
</div>
<% end %>
<%= render "shared/footer" %>

app/views/topics/index.html.erb
<%= render "shared/header" %>

 <div class="kind_wrapper">
  <span style="font-family: Comic Sans MS;">
    <div class="index_kind_japanese">
    <a href="/kind_japanese">
    「やさしい<ruby>日本語<rt>にほんご</rt></ruby>」を あなたは <ruby>知<rt>し</rt></ruby>って いますか？ </a>
    </div>
    </span>
  </div>

  <% breadcrumb :root %>
  
<div class="flower_main">
<div class="flower"><%= image_tag('flower.png',size: '1025x530')  %></div>
</div>

<div class="topic_index_main">
<%= search_form_for @p, url: search_topics_path do |f| %>

  <div class="topic_choice_sentence" >
<ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>選<rt>えら</rt></ruby>びます
  </div>
<br>
  <div class="topic_choice_pulldown"><%= f.collection_select :sentence_id_eq, Sentence.all , :id, :name %></div>

  <div><%= button_tag type: :submit ,class: "search_btn",value: "search_buttton" do %>
       <%= image_tag('search.png',size: '40x40')  %>
  <% end %>
  </div>
<br>
</div>




<div class='main'>
 <div class='inner'>
    <% if @topics[0] != nil %>
     <ul class="topic_lists">
        <% @topics.each do |topic| %>

        

    <%= link_to topic_path(topic.id) do %>
     
    <div class="card_wrapper">
    <br>
      <li class="card">
       <li class="card_name"><span><%= topic.user.id %> <%= topic.user.name %></span> </li>
       <br>
          <li class="topic_card_sentence"><%= topic.sentence.name %></li>
   <br>
          <li class="card_birth"><span>私(わたし)は  <%= topic.user.birth_country %> 出身(しゅっしん)です</span> </li>
      
          <li class="card_pref"><span>私(わたし)は <%= topic.user.prefecture.name %>に 住(す)んでいます</span> </li>
      <br>
      <% if  topic.user.identity.present? %>
        <li class="card_identity"> <span>私(わたし)は Facebookを 使(つか)います</span><li>
      
         
          <li class="card_identity_content"> <span><%= topic.user.identity %></span> </li>
       <% end %>
      <br> 
          <li class="card_updated_time"><span><%= topic.updated_at.strftime('%Y/%m/%d') %></span></li>
        
     </li>
     
   </div>
 
     <% end %>
    <% end %>
  
  <% end %>
  </ul>
 </div>
</div>
<% end %>

<br>


<%# 投稿ボタン%>

<%= link_to(new_topic_path, class: 'post-btn') do %>
  <span class='post-btn-text'><ruby>送<rt>おく</rt></ruby>ります</span>
  <%= image_tag 'post.png' , size: '185x50' ,class: "post-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/topics/new.html.erb
 <%= render "shared/header" %>

 <% breadcrumb :topics %>

<div class="new_container">
 <div class="new_wrapper">
    
    <%= form_with model:@topic, local: true do |f| %>

        <%= render 'shared/error_messages', model: f.object %>

    <div class="new_field">
    <div class="new_choice_sentence"> <ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>選<rt>えら</rt></ruby>びます</div>
      <br>
    <%= f.collection_select(:sentence_id, Sentence.all, :id, :name, {}, {class:"new_select-box", id:"topic-sentence"}) %>
    
    </div>


   <br>

   <div class="new_field">

      <div class="new_explain_sentence"><ruby>私<rt>わたし</rt></ruby>は この<ruby>文章<rt>ぶんしょう</rt></ruby>について <ruby>説明<rt>せつめい</rt></ruby>します</div>
      <%= f.text_area :description, autofocus: true, autocomplete: "description", :placeholder => "はじめまして、私は〇〇です..."%>
    </div>

    <div class="actions">
      <div><%= button_tag type: :submit ,class: "explain_btn" do %>
       <%= image_tag('explain.png',size: '40x40')  %>
    <% end %>

    </div>
 </div>  
</div>


</div>
</div>
<% end %>
 <%= render "shared/footer" %>

app/views/topics/search.html.erb
 <%= render "shared/header" %>

<% breadcrumb :topiced, @topic %>

<div class='topic_choice_main'>
 <div class='inner'>


    <% if @results.length !=0 %>
    <ul class="topic_lists">
      <% @results.each do |result| %>
    
    <div class="card_wrapper_search">
    <br>
      <li class="card">
 
     <li class="card_name"> <span><%= result.user.id %> <%= result.user.name %></span></li>
      <br>
     <li class="card_birth_search"> <span>私(わたし)は<br><%= result.user.birth_country %><br>出身(しゅっしん)です</span></li>
      <br>
      <li class="card_pref_search"><span>私(わたし)は<br><%= result.user.prefecture.name %>に<br> 住(す)んでいます</span> </li>
      
    <li class="card_updated_time"><span><%= result.user.updated_at.strftime('%Y/%m/%d')  %></span></li>

    </li>
     
    </div>

   <div class="search_right_wrapper">
      <div class="search_description"><%= simple_format(result.description) %>
      </div>
  </div>

    <% end %>
    
    </ul>
  </div>
</div>

<%= render "shared/footer" %>

<% else %>

<div class="serach_not_main">
<br>
  <div class="search_not">あなたが 選んだ文章は ありません</div>
<br>
  <div class="search_return"><%= link_to '「やさしいHP」へ 戻りましょう', root_path %> </div>
  </div>
  <br>
  <br>
   <%= image_tag('return.png',size: '200x200',class: "return_btn ")  %> 
<% end %>

<% if @results.length == 0 %>
<footer>

  <div class="container_f">
    <div class="footer_logo">
      <%= link_to image_tag("logo.png"), root_path, class:"footer_image_logo" %>
    </div>
    <div class="copy_right"><p>Copyright © 2021 K.T. Inc. All Rights Reserved. </p></div>
    
  </div>

</footer>
<% end %>
<br>

app/views/topics/show.html.erb
<%= render "shared/header" %>

<% breadcrumb :topic, @topic %>

<div class='main'>
 <div class='inner'>
   <ul class="topic_lists">
     <div class="card_wrapper_show">
      <br>
       <li class="card">

            <li class="card_name"> <span><%= @topic.user.id %> <%= @topic.user.name %></span></li>
              <br>
           <li class="card_birth_show"> <span>私(わたし)は<br><%= @topic.user.birth_country %><br>出身(しゅっしん)です</span></li>
            <br>
           <li class="card_pref_show"><span>私(わたし)は<br><%= @topic.user.prefecture.name %>に<br> 住(す)んでいます</span> </li>
            
           <li class="card_updated_time"><span><%= @topic.user.updated_at.strftime('%Y/%m/%d')  %></span></li>
            
        </li>
      </div>
    </ul>   
  </div>

 <div class="show_description_main">
    <div class="show_description_wrapper">
        <div class="show_description"><%=simple_format(@topic.description)%></div>
       
    </div>
 </div>

 <br>

 <% if user_signed_in? %>
  <%if current_user.id == @topic.user_id %>
  <div class="show_under">
   <div class="show_sentence">
   <ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>書<rt>か</rt></ruby>き<ruby>直<rt>なお</rt></ruby>します</div>
    <%= link_to image_tag("edit.png", method: :get, class: "edit-btn"), edit_topic_path(@topic.id) %>  
  
    <div class="or-text">もしくは</div>
    <br>
   <div class="show_sentence">
   <ruby>私<rt>わたし</rt></ruby>は <ruby>文章<rt>ぶんしょう</rt></ruby>を <ruby>消<rt>け</rt></ruby>します</div>
    <div><%= link_to image_tag("delete.png"), topic_path, method: :delete, class:"delete-btn",id: "delete-btn" ,data: { confirm: 'あなたは 本当(ほんとう)に この文章(ぶんしょう)を 消(け)しますか？' } %></div>



  </div>
   <% end %>
    <% end %>
  </div>
  
</div>
<%= render "comments/new" %>

<%= render "shared/footer" %>